services:
  backend:
    image: alieldor1/tourivo-backend:latest
    environment:
      - PORT=3000
      - MONGO_URI=db_connection
      - OPENAI_API_KEY=key
      - JWT_SECRET_KEY=jwt
      - GOOGLE_CLOUD_CREDENTIALS=./credentials/google-cloud-key.json

    restart: always
    ports:
      - 3000:3000
    # command: sh -c "cp .env.example .env && node index.js"
  
  